version: "2.4"

networks:
  bitcoinstacknet:
    driver: bridge

volumes:
  alice_data:
  bob_data:
  bob2_data:
  bob3_data:
  carol_data:
  dave_data:
  emma_data:
  frank_data:

services:
  alice:
    container_name: ${COMPOSE_PROJECT_NAME}_alice
    image: bitcoinstack/lnd:0.11.1-alpine
    # restart: unless-stopped
    command: [
      "--noseedbackup",
      "--alias=alice",
      "--listen=0.0.0.0:${ALICE_PORT}",
      "--rpclisten=0.0.0.0:${ALICE_RPC_PORT}",
      "--restlisten=0.0.0.0:${ALICE_REST_PORT}",
      "--tlsextradomain=${ALICE_HOST}",
      "--tlsextraip=0.0.0.0",
      "--debuglevel=trace",
      "--autopilot.allocation=0",
      "--protocol.wumbo-channels",
      "--bitcoin.active",
      "--bitcoin.regtest",
      "--bitcoin.node=bitcoind",
      "--bitcoind.rpchost=${BITCOIN_HOST}:${BITCOIN_RPC_PORT}",
      "--bitcoind.rpcuser=${BITCOIN_RPC_USER}",
      "--bitcoind.rpcpass=${BITCOIN_RPC_PASSWORD}",
      "--bitcoind.zmqpubrawtx=tcp://${BITCOIN_HOST}:${BITCOIN_ZMQ_TX_PORT}",
      "--bitcoind.zmqpubrawblock=tcp://${BITCOIN_HOST}:${BITCOIN_ZMQ_BLOCK_PORT}"
    ]
    depends_on:
      - bitcoin
    networks:
      bitcoinstacknet:
        aliases:
          - ${ALICE_HOST}
    ports:
      - "127.0.0.1:${ALICE_RPC_PORT}:${ALICE_RPC_PORT}"
      - "127.0.0.1:${ALICE_REST_PORT}:${ALICE_REST_PORT}"
    volumes:
      - alice_data:/home/lnd/.lnd

  bob:
    container_name: ${COMPOSE_PROJECT_NAME}_bob
    image: bitcoinstack/lnd:0.11.1-alpine
    # restart: unless-stopped
    command: [
      "--noseedbackup",
      "--alias=bob",
      "--listen=0.0.0.0:${BOB_PORT}",
      "--rpclisten=0.0.0.0:${BOB_RPC_PORT}",
      "--restlisten=0.0.0.0:${BOB_REST_PORT}",
      "--tlsextradomain=${BOB_HOST}",
      "--tlsextraip=0.0.0.0",
      "--autopilot.allocation=0",
      "--accept-keysend",
      "--debuglevel=trace",
      "--protocol.wumbo-channels",
      "--bitcoin.active",
      "--bitcoin.regtest",
      "--bitcoin.node=bitcoind",
      "--bitcoind.rpchost=${BITCOIN_HOST}:${BITCOIN_RPC_PORT}",
      "--bitcoind.rpcuser=${BITCOIN_RPC_USER}",
      "--bitcoind.rpcpass=${BITCOIN_RPC_PASSWORD}",
      "--bitcoind.zmqpubrawtx=tcp://${BITCOIN_HOST}:${BITCOIN_ZMQ_TX_PORT}",
      "--bitcoind.zmqpubrawblock=tcp://${BITCOIN_HOST}:${BITCOIN_ZMQ_BLOCK_PORT}"
    ]
    depends_on:
      - bitcoin
    networks:
      bitcoinstacknet:
        aliases:
          - ${BOB_HOST}
    ports:
      - "127.0.0.1:${BOB_RPC_PORT}:${BOB_RPC_PORT}"
      - "127.0.0.1:${BOB_REST_PORT}:${BOB_REST_PORT}"
    volumes:
      - bob_data:/home/lnd/.lnd

  bob2:
    container_name: ${COMPOSE_PROJECT_NAME}_bob2
    image: bitcoinstack/lnd:0.11.1-alpine
    # restart: unless-stopped
    command: [
      "--noseedbackup",
      "--alias=bob2",
      "--listen=0.0.0.0:${BOB2_PORT}",
      "--rpclisten=0.0.0.0:${BOB2_RPC_PORT}",
      "--restlisten=0.0.0.0:${BOB2_REST_PORT}",
      "--tlsextradomain=${BOB2_HOST}",
      "--tlsextraip=0.0.0.0",
      "--autopilot.allocation=0",
      "--accept-keysend",
      "--protocol.wumbo-channels",
      "--bitcoin.active",
      "--bitcoin.regtest",
      "--bitcoin.node=bitcoind",
      "--bitcoind.rpchost=${BITCOIN_HOST}:${BITCOIN_RPC_PORT}",
      "--bitcoind.rpcuser=${BITCOIN_RPC_USER}",
      "--bitcoind.rpcpass=${BITCOIN_RPC_PASSWORD}",
      "--bitcoind.zmqpubrawtx=tcp://${BITCOIN_HOST}:${BITCOIN_ZMQ_TX_PORT}",
      "--bitcoind.zmqpubrawblock=tcp://${BITCOIN_HOST}:${BITCOIN_ZMQ_BLOCK_PORT}"
    ]
    depends_on:
      - bitcoin
    networks:
      bitcoinstacknet:
        aliases:
          - ${BOB2_HOST}
    ports:
      - "127.0.0.1:${BOB2_RPC_PORT}:${BOB2_RPC_PORT}"
      - "127.0.0.1:${BOB2_REST_PORT}:${BOB2_REST_PORT}"
    volumes:
      - bob2_data:/home/lnd/.lnd

  bob3:
    container_name: ${COMPOSE_PROJECT_NAME}_bob3
    image: bitcoinstack/lnd:0.11.1-alpine
    # restart: unless-stopped
    command: [
      "--noseedbackup",
      "--alias=bob3",
      "--listen=0.0.0.0:${BOB3_PORT}",
      "--rpclisten=0.0.0.0:${BOB3_RPC_PORT}",
      "--restlisten=0.0.0.0:${BOB3_REST_PORT}",
      "--tlsextradomain=${BOB3_HOST}",
      "--tlsextraip=0.0.0.0",
      "--autopilot.allocation=0",
      "--accept-keysend",
      "--protocol.wumbo-channels",
      "--bitcoin.active",
      "--bitcoin.regtest",
      "--bitcoin.node=bitcoind",
      "--bitcoind.rpchost=${BITCOIN_HOST}:${BITCOIN_RPC_PORT}",
      "--bitcoind.rpcuser=${BITCOIN_RPC_USER}",
      "--bitcoind.rpcpass=${BITCOIN_RPC_PASSWORD}",
      "--bitcoind.zmqpubrawtx=tcp://${BITCOIN_HOST}:${BITCOIN_ZMQ_TX_PORT}",
      "--bitcoind.zmqpubrawblock=tcp://${BITCOIN_HOST}:${BITCOIN_ZMQ_BLOCK_PORT}"
    ]
    depends_on:
      - bitcoin
    networks:
      bitcoinstacknet:
        aliases:
          - ${BOB3_HOST}
    ports:
      - "127.0.0.1:${BOB3_RPC_PORT}:${BOB3_RPC_PORT}"
      - "127.0.0.1:${BOB3_REST_PORT}:${BOB3_REST_PORT}"
    volumes:
      - bob3_data:/home/lnd/.lnd

  carol:
    container_name: ${COMPOSE_PROJECT_NAME}_carol
    image: bitcoinstack/clightning:0.9.1-alpine
    command: [
      "--alias=carol",
      "--network=regtest",
      "--large-channels",
      "--addr=0.0.0.0:${CAROL_PORT}",
      "--bitcoin-cli=/bitcoin/bitcoin-cli",
      "--bitcoin-datadir=/bitcoin",
      "--bitcoin-rpcconnect=${BITCOIN_HOST}",
      "--bitcoin-rpcport=${BITCOIN_RPC_PORT}",
      "--bitcoin-rpcuser=${BITCOIN_RPC_USER}",
      "--bitcoin-rpcpassword=${BITCOIN_RPC_PASSWORD}"
    ]
    depends_on:
      - bitcoin
    networks:
      bitcoinstacknet:
        aliases:
          - ${CAROL_HOST}
    volumes:
      - carol_data:/home/clightning/.lightning
      - ./clightning/plugins:/home/clightning/.lightning/plugins
      - bitcoin_shared:/bitcoin

  dave:
    container_name: ${COMPOSE_PROJECT_NAME}_dave
    image: bitcoinstack/clightning:0.9.1-alpine
    command: [
      "--alias=dave",
      "--network=liquid-regtest",
      "--addr=0.0.0.0:${DAVE_PORT}",
      "--large-channels",
      "--bitcoin-cli=/elements/elements-cli",
      "--bitcoin-datadir=/elements",
      "--bitcoin-rpcconnect=${ELEMENTS_HOST}",
      "--bitcoin-rpcport=${ELEMENTS_RPC_PORT}",
      "--bitcoin-rpcuser=${ELEMENTS_RPC_USER}",
      "--bitcoin-rpcpassword=${ELEMENTS_RPC_PASSWORD}"
    ]
    depends_on:
      - elements
    networks:
      bitcoinstacknet:
        aliases:
          - ${DAVE_HOST}
    volumes:
      - dave_data:/home/clightning/.lightning
      - elements_shared:/elements

  emma:
    container_name: ${COMPOSE_PROJECT_NAME}_emma
    image: bitcoinstack/clightning:0.9.1-alpine
    command: [
      "--alias=emma",
      "--network=liquid-regtest",
      "--addr=0.0.0.0:${EMMA_PORT}",
      "--large-channels",
      "--bitcoin-cli=/elements/elements-cli",
      "--bitcoin-datadir=/elements",
      "--bitcoin-rpcconnect=${ELEMENTS_HOST}",
      "--bitcoin-rpcport=${ELEMENTS_RPC_PORT}",
      "--bitcoin-rpcuser=${ELEMENTS_RPC_USER}",
      "--bitcoin-rpcpassword=${ELEMENTS_RPC_PASSWORD}"
    ]
    depends_on:
      - elements
    networks:
      bitcoinstacknet:
        aliases:
          - ${EMMA_HOST}
    volumes:
      - emma_data:/home/clightning/.lightning
      - elements_shared:/elements

  frank:
    container_name: ${COMPOSE_PROJECT_NAME}_frank
    image: bitcoinstack/eclair:0.4.1
    command: ["bash", "eclair-node/bin/eclair-node.sh"]
    environment:
      - |
        JAVA_TOOL_OPTIONS=
        -Xmx512m
        -Declair.chain=regtest
        -Declair.datadir=/data
        -Declair.node-alias=frank
        -Declair.server.port=${FRANK_PORT}
        -Declair.bitcoind.host=${BITCOIN_HOST}
        -Declair.bitcoind.rpcport=${BITCOIN_RPC_PORT}
        -Declair.bitcoind.rpcuser=${BITCOIN_RPC_USER}
        -Declair.bitcoind.rpcpassword=${BITCOIN_RPC_PASSWORD}
        -Declair.bitcoind.zmqtx=tcp://${BITCOIN_HOST}:${BITCOIN_ZMQ_TX_PORT}
        -Declair.bitcoind.zmqblock=tcp://${BITCOIN_HOST}:${BITCOIN_ZMQ_BLOCK_PORT}
        -Declair.api.enabled=true
        -Declair.api.port=${FRANK_REST_PORT}
        -Declair.api.password=password
        -Declair.api.binding-ip=0.0.0.0
    depends_on:
      - bitcoin
    networks:
      bitcoinstacknet:
        aliases:
          - ${FRANK_HOST}
    ports:
      - "127.0.0.1:${FRANK_REST_PORT}:${FRANK_REST_PORT}"
    volumes:
      - frank_data:/data

  demo:
    container_name: ${COMPOSE_PROJECT_NAME}_demo
    image: bitcoinstack/demo:0.1
    restart: unless-stopped
    command: ['node', 'subscriber.js']
    depends_on:
      - bitcoin
      - alice
    environment:
      - BITCOIN_HOST
      - BITCOIN_RPC_PORT
      - BITCOIN_RPC_USER
      - BITCOIN_RPC_PASSWORD
      - ALICE_HOST
      - ALICE_RPC_PORT
    volumes:
      - ./node/app:/usr/src/app
      - alice_data:/lnd:ro
    networks:
      - bitcoinstacknet

  rtl:
    container_name: ${COMPOSE_PROJECT_NAME}_rtl
    image: shahanafarooqui/rtl:0.9.0
    # restart: unless-stopped
    ports:
      - "127.0.0.1:${RTL_PORT}:${RTL_PORT}"
    depends_on:
      - alice
      - bob
    environment:
      - PORT=${RTL_PORT}
      - HOST=${RTL_HOST}
      - RTL_CONFIG_PATH=/RTL/config
    volumes:
      - ./rtl:/RTL/config
      - alice_data:/alice:ro
      - bob_data:/bob:ro
    networks:
      - bitcoinstacknet